package View;

import java.util.List;
import Model.Cliente;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.JTextField;
import DAO.ClienteDAO;

public class ClienteConsulta extends javax.swing.JInternalFrame {
	private boolean modoProcura = false;
	private JTextField campo;
	
    /**
     * Creates new form FormConsultarClientes
     */
    public ClienteConsulta() {
        initComponents();
    }
	
	public ClienteConsulta(boolean modoProcura, JTextField campo) {
        this.modoProcura = modoProcura;
		this.campo = campo;
		
		initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabelaMenu = new javax.swing.JPopupMenu();
        opAlterar = new javax.swing.JMenuItem();
        opIncluir = new javax.swing.JMenuItem();
        opExcluir = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JSeparator();
        pnlConsultarClientes = new javax.swing.JPanel();
        lblNome = new javax.swing.JLabel();
        cmdBuscar = new javax.swing.JButton();
        txtNome = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaResultado = new javax.swing.JTable();

        opAlterar.setMnemonic('A');
        opAlterar.setText("Alterar");
        opAlterar.setComponentPopupMenu(tabelaMenu);
        opAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opAlterarActionPerformed(evt);
            }
        });
        tabelaMenu.add(opAlterar);

        opIncluir.setMnemonic('I');
        opIncluir.setText("Incluir");
        opIncluir.setToolTipText("");
        opIncluir.setComponentPopupMenu(tabelaMenu);
        opIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opIncluirActionPerformed(evt);
            }
        });
        tabelaMenu.add(opIncluir);

        opExcluir.setMnemonic('E');
        opExcluir.setText("Excluir");
        opExcluir.setComponentPopupMenu(tabelaMenu);
        opExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opExcluirActionPerformed(evt);
            }
        });
        tabelaMenu.add(opExcluir);

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Consultar Clientes");

        lblNome.setText("Nome:");

        cmdBuscar.setText("Buscar");
        cmdBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdBuscarActionPerformed(evt);
            }
        });

        tabelaResultado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Nome", "CPF/CNPJ"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelaResultado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tabelaResultadoMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(tabelaResultado);

        javax.swing.GroupLayout pnlConsultarClientesLayout = new javax.swing.GroupLayout(pnlConsultarClientes);
        pnlConsultarClientes.setLayout(pnlConsultarClientesLayout);
        pnlConsultarClientesLayout.setHorizontalGroup(
            pnlConsultarClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlConsultarClientesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlConsultarClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(pnlConsultarClientesLayout.createSequentialGroup()
                        .addComponent(lblNome)
                        .addGap(10, 10, 10)
                        .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 409, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 274, Short.MAX_VALUE)
                        .addComponent(cmdBuscar)))
                .addContainerGap())
        );
        pnlConsultarClientesLayout.setVerticalGroup(
            pnlConsultarClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlConsultarClientesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlConsultarClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlConsultarClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cmdBuscar))
                    .addGroup(pnlConsultarClientesLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(lblNome)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 267, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlConsultarClientes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlConsultarClientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 16, Short.MAX_VALUE))
        );

        setBounds(0, 0, 825, 358);
    }// </editor-fold>//GEN-END:initComponents

    private void cmdBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdBuscarActionPerformed
        List<Cliente> resultado = null;
		try {
			resultado = ClienteDAO.getClientesPorNome(txtNome.getText());
		} catch (Exception ex) {
		}
		
        DefaultTableModel model = (DefaultTableModel) tabelaResultado.getModel();		
		model.setRowCount(0);
        
        if (resultado == null || resultado.size() <= 0) {
            JOptionPane.showMessageDialog(rootPane, "A pesquisa não retornou resultados ",
                    "Sem resultados", JOptionPane.ERROR_MESSAGE);            
            return;
        }
        
        int size = resultado.size();        
        
        for (int i = 0; i < size; i++){
            Cliente cli = resultado.get(i);
            
            if (cli != null) {
                Object[] row = new Object[8];
                
                row[0] = cli.getId();
                row[1] = cli.getNome();
                model.addRow(row);
            }
        }
    }//GEN-LAST:event_cmdBuscarActionPerformed

    private void tabelaResultadoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaResultadoMousePressed

    }//GEN-LAST:event_tabelaResultadoMousePressed

    private void opAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opAlterarActionPerformed
       
    }//GEN-LAST:event_opAlterarActionPerformed

    private void opIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opIncluirActionPerformed
       
    }//GEN-LAST:event_opIncluirActionPerformed

    private void opExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opExcluirActionPerformed
    
    }//GEN-LAST:event_opExcluirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClienteConsulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClienteConsulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClienteConsulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClienteConsulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ClienteConsulta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmdBuscar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblNome;
    private javax.swing.JMenuItem opAlterar;
    private javax.swing.JMenuItem opExcluir;
    private javax.swing.JMenuItem opIncluir;
    private javax.swing.JPanel pnlConsultarClientes;
    private javax.swing.JPopupMenu tabelaMenu;
    private javax.swing.JTable tabelaResultado;
    private javax.swing.JTextField txtNome;
    // End of variables declaration//GEN-END:variables
	
	public void selecionar(){
		DefaultTableModel model = (DefaultTableModel) tabelaResultado.getModel();
		this.campo.setText(String.valueOf(model.getValueAt(tabelaResultado.getSelectedRow(), 0)));
		
		this.campo.grabFocus();
		dispose();
	}
}