/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Model.ItemPedido;
import Model.Produto;
import Controller.ProdutoController;
import DAO.ProdutoDAO;
import LojaDeMoveis.Raiz;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author andrey.santos
 */
public class ItemVendaCadastro extends javax.swing.JDialog {

    ItemPedido item = null;

    /**
     * Creates new form ItemVendaCadastro
     */
    public ItemVendaCadastro(javax.swing.JInternalFrame parent, boolean modal) {
        this.setModal(modal);

        initComponents();

        item = new ItemPedido();
        eventoGrade();
        init();
    }

    public ItemVendaCadastro(boolean modal, ItemPedido item) {
        if (item.getCodigoProduto() != null && !item.getCodigoProduto().equals("")) {
            txtCodigoProduto.setText(item.getCodigoProduto());
            txtVlUnitario.setText(String.valueOf(item.getVlUni()));
            txtVlTotal.setText(String.valueOf(item.getVlTotal()));
            txtQuantidade.setText(String.valueOf(item.getQuantidade()));
        }

        this.item = item;
        initComponents();
        eventoGrade();
        init();
    }

    public void eventoGrade() {
        // coloca evento de mudança na tabela
        tabelaProdutos.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            public void valueChanged(ListSelectionEvent e) {
                if (!e.getValueIsAdjusting()) {
                    DefaultTableModel model = (DefaultTableModel) tabelaProdutos.getModel();
                    if (model == null || model.getRowCount() == 0 || tabelaProdutos.getSelectedRow() < 0) {
                        return;
                    }

                    txtCodigoProduto.setText(String.valueOf(model.getValueAt(tabelaProdutos.getSelectedRow(), 0)));
                    txtNome.setText(String.valueOf(model.getValueAt(tabelaProdutos.getSelectedRow(), 1)));
                    txtVlUnitario.setText(Raiz.getStringNumber(String.valueOf(model.getValueAt(tabelaProdutos.getSelectedRow(), 2))));
                    //txtQuantidade.setText(Raiz.getStringNumber(String.valueOf(model.getValueAt(tabelaProdutos.getSelectedRow(), 3))));
                }
            }
        });
    }

    public void init() {
        List<Produto> listaProdutos;
        
        listaProdutos = null;
        
        //try{
        //	if (this.chkSomenteComEstoque.isSelected()) {
        //		listaProdutos = ServicoProduto.procurarProduto("", "", 1, 0);
        //	}else{
        //		listaProdutos = ServicoProduto.procurarProduto();
        //	}
        //}catch(Exception erro){
        //}
        
        listaProdutos = ProdutoDAO.getProdutos();
        
        DefaultTableModel model = (DefaultTableModel) tabelaProdutos.getModel();
        model.setRowCount(0);

        //if (listaProdutos == null) {
        //	return;
        //}
        int size = listaProdutos.size();

        for (int i = 0; i < size; i++) {
            Produto produto = listaProdutos.get(i);

            if (produto != null) {
                Object[] row = new Object[4];

                row[0] = produto.getId();
                row[1] = produto.getModelo();
                row[2] = produto.getPreco();
                row[3] = produto.getQuantidade();

                model.addRow(row);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblValorTotal = new javax.swing.JLabel();
        lblValorUnitário = new javax.swing.JLabel();
        txtCodigoProduto = new javax.swing.JTextField();
        lblNome = new javax.swing.JLabel();
        lblQuantidade = new javax.swing.JLabel();
        lblCódigo = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        cmdOk = new javax.swing.JButton();
        cmdCancelar = new javax.swing.JButton();
        txtQuantidade = new javax.swing.JFormattedTextField();
        txtVlUnitario = new javax.swing.JFormattedTextField();
        txtVlTotal = new javax.swing.JFormattedTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelaProdutos = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Incluir item de venda");
        setModal(true);
        setResizable(false);

        lblValorTotal.setText("Vl.Total");

        lblValorUnitário.setText("Vl. Unitário");

        txtCodigoProduto.setBackground(Raiz.getCorObrigatorio());
        txtCodigoProduto.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCodigoProdutoFocusLost(evt);
            }
        });
        txtCodigoProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodigoProdutoActionPerformed(evt);
            }
        });
        txtCodigoProduto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCodigoProdutoKeyPressed(evt);
            }
        });

        lblNome.setText("Nome");

        lblQuantidade.setText("Qtde.");

        lblCódigo.setText("Código");

        txtNome.setEditable(false);
        txtNome.setDisabledTextColor(new java.awt.Color(0, 0, 0));

        cmdOk.setMnemonic('o');
        cmdOk.setText("OK");
        cmdOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdOkActionPerformed(evt);
            }
        });

        cmdCancelar.setMnemonic('c');
        cmdCancelar.setText("Cancelar");
        cmdCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdCancelarActionPerformed(evt);
            }
        });

        txtQuantidade.setBackground(Raiz.getCorObrigatorio());
        txtQuantidade.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        txtQuantidade.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        txtQuantidade.setText("0");
        txtQuantidade.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtQuantidadeFocusLost(evt);
            }
        });
        txtQuantidade.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtQuantidadeKeyPressed(evt);
            }
        });

        txtVlUnitario.setEditable(false);
        txtVlUnitario.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        txtVlUnitario.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtVlUnitario.setText("0");
        txtVlUnitario.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtVlUnitarioFocusLost(evt);
            }
        });

        txtVlTotal.setEditable(false);
        txtVlTotal.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        txtVlTotal.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtVlTotal.setText("0");
        txtVlTotal.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtVlTotalFocusLost(evt);
            }
        });

        tabelaProdutos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Produto", "Vl. Unitário", "Quantidade"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelaProdutos.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane2.setViewportView(tabelaProdutos);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblCódigo)
                        .addGap(5, 5, 5)
                        .addComponent(txtCodigoProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16)
                        .addComponent(lblNome)
                        .addGap(9, 9, 9)
                        .addComponent(txtNome))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblQuantidade)
                                .addGap(6, 6, 6)
                                .addComponent(txtQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblValorUnitário)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtVlUnitario, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblValorTotal)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtVlTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(339, 339, 339)
                                .addComponent(cmdOk, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(cmdCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jScrollPane2))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtCodigoProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCódigo)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNome))
                .addGap(32, 32, 32)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblQuantidade)
                        .addComponent(txtQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblValorUnitário)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblValorTotal)
                        .addComponent(txtVlUnitario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtVlTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cmdOk)
                    .addComponent(cmdCancelar))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cmdOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdOkActionPerformed
        if (!validarProduto()) {
            return;
        }

        if (!validarObrigatorio()) {
            return;
        }

        item.setCodigoProduto(txtCodigoProduto.getText());
        item.setQuantidade((int) Raiz.getNumber(txtQuantidade.getText()));
        item.setVlUni(Raiz.getNumber(txtVlUnitario.getText()));
        item.setVlTotal(Raiz.getNumber(txtVlTotal.getText()));

        dispose();
    }//GEN-LAST:event_cmdOkActionPerformed

    private void cmdCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdCancelarActionPerformed
        item.setCodigoProduto(null);

        if (Raiz.verifSaida(jPanel1)) {
            dispose();
        } else {
            return;
        }
    }//GEN-LAST:event_cmdCancelarActionPerformed

    private void txtQuantidadeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtQuantidadeFocusLost
        double total = 0, uni = 0, qtEst;

        //txtQuantidade.setText(Raiz.getStringEmptyDefault(txtQuantidade.getText(), "0"));
        // valida estoque
        //DefaultTableModel model = (DefaultTableModel)tabelaProdutos.getModel();
        //if (!(model == null || model.getRowCount() == 0 || tabelaProdutos.getSelectedRow() < 0)) {
        //	qtEst = Raiz.getNumber(String.valueOf(model.getValueAt(tabelaProdutos.getSelectedRow(), 3)));
        //	if (qtEst == 0 || Raiz.getNumber(txtQuantidade.getText()) > qtEst) {
        //		txtQuantidade.setText("0");
        //		JOptionPane.showMessageDialog(null, "Quantidade selecionada não disponível em estoque!", "Atenção", JOptionPane.WARNING_MESSAGE);
        //		return;
        //	}
        //}
        // calcula valores totais
        uni = Raiz.getNumber(txtVlUnitario.getText());
        total = Raiz.getNumber(txtQuantidade.getText()) * uni;

        txtVlTotal.setText(Raiz.getStringNumber(String.valueOf(total)));
    }//GEN-LAST:event_txtQuantidadeFocusLost

    private void txtVlUnitarioFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtVlUnitarioFocusLost
        txtVlUnitario.setText(Raiz.getStringEmptyDefault(txtVlUnitario.getText(), "0"));
    }//GEN-LAST:event_txtVlUnitarioFocusLost

    private void txtVlTotalFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtVlTotalFocusLost
        txtVlTotal.setText(Raiz.getStringEmptyDefault(txtVlTotal.getText(), "0"));
    }//GEN-LAST:event_txtVlTotalFocusLost

    private void txtCodigoProdutoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCodigoProdutoFocusLost
        validarProduto();
    }//GEN-LAST:event_txtCodigoProdutoFocusLost

    private void txtCodigoProdutoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodigoProdutoKeyPressed
        String field = txtCodigoProduto.getText();
        int qtCarac = field.length();

        if (qtCarac > 15) {
            field = field.substring(0, field.length() - 1);
            txtCodigoProduto.setText(field);
        }
    }//GEN-LAST:event_txtCodigoProdutoKeyPressed

    private void txtQuantidadeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtQuantidadeKeyPressed
        String field = txtQuantidade.getText();
        int qtCarac = field.length();

        if (qtCarac > 10) {
            field = field.substring(0, field.length() - 1);
            txtQuantidade.setText(field);
        }
    }//GEN-LAST:event_txtQuantidadeKeyPressed

    private void txtCodigoProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodigoProdutoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodigoProdutoActionPerformed

    public boolean validarProduto() {
        if (txtCodigoProduto.getText().trim().equals("")) {
            return true;
        }

        DefaultTableModel model = (DefaultTableModel) tabelaProdutos.getModel();

        for (int i = 0; i < model.getRowCount(); i++) {
            if (String.valueOf(model.getValueAt(i, 0)).trim().equals(txtCodigoProduto.getText().trim())) {
                tabelaProdutos.setRowSelectionInterval(i, i);
                return true;
            }
        }

        JOptionPane.showMessageDialog(null, "Produto não encontrado!", "Atenção", JOptionPane.WARNING_MESSAGE);
        txtCodigoProduto.grabFocus();

        if (tabelaProdutos.getRowCount() > 0) {
            tabelaProdutos.setRowSelectionInterval(0, 0);
        }

        return false;
    }

    public boolean validarObrigatorio() {
        boolean retorno = true;

        if (txtQuantidade.getText().trim().equals("0") || txtQuantidade.getText().trim().equals("")) {
            retorno = false;
            txtNome.grabFocus();
        } else if (txtCodigoProduto.getText().trim().equals("")) {
            retorno = false;
            txtCodigoProduto.grabFocus();
        }

        if (!retorno) {
            JOptionPane.showMessageDialog(null, "Campo de preenchimento obrigatório vazio!", "Atenção", JOptionPane.WARNING_MESSAGE);
        }

        return retorno;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ItemVendaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ItemVendaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ItemVendaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ItemVendaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ItemVendaCadastro dialog = new ItemVendaCadastro(new javax.swing.JInternalFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmdCancelar;
    private javax.swing.JButton cmdOk;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblCódigo;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblQuantidade;
    private javax.swing.JLabel lblValorTotal;
    private javax.swing.JLabel lblValorUnitário;
    private javax.swing.JTable tabelaProdutos;
    private javax.swing.JTextField txtCodigoProduto;
    private javax.swing.JTextField txtNome;
    private javax.swing.JFormattedTextField txtQuantidade;
    private javax.swing.JFormattedTextField txtVlTotal;
    private javax.swing.JFormattedTextField txtVlUnitario;
    // End of variables declaration//GEN-END:variables
}
