/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Model.Cliente;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import Model.Pedido;
import Controller.ClienteController;
import Controller.PedidoController;
import LojaDeMoveis.Raiz;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import javax.swing.table.DefaultTableCellRenderer;
import DAO.PedidoDAO;
import Model.ItemPedido;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;

/**
 *
 * @author Caio
 */
public class VendaRelatorio extends javax.swing.JFrame {

    /**
     * Creates new form Vendas_Relatorio2
     */
    static List<ItemPedido> listItem = null;

    public VendaRelatorio() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        cmdBuscar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaResultado = new javax.swing.JTable();
        lblData = new javax.swing.JLabel();
        txtDtVendaDe = new javax.swing.JFormattedTextField();
        lblAté = new javax.swing.JLabel();
        txtDtVendaAte = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Relatório de vendas");

        cmdBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/buscar.png"))); // NOI18N
        cmdBuscar.setText("Buscar");
        cmdBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdBuscarActionPerformed(evt);
            }
        });

        tabelaResultado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "IdPedido", "Cliente", "Dt. Venda", "Vl.Total", "Vl. Desconto", "Forma de pagto", "Observações"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabelaResultado);

        lblData.setText("Data da Venda:");

        try {
            txtDtVendaDe.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtDtVendaDe.setFocusLostBehavior(javax.swing.JFormattedTextField.COMMIT);
        txtDtVendaDe.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtDtVendaDeFocusLost(evt);
            }
        });
        txtDtVendaDe.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtDtVendaDeKeyReleased(evt);
            }
        });

        lblAté.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAté.setText("até");

        try {
            txtDtVendaAte.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtDtVendaAte.setFocusLostBehavior(javax.swing.JFormattedTextField.COMMIT);
        txtDtVendaAte.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtDtVendaAteFocusLost(evt);
            }
        });
        txtDtVendaAte.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtDtVendaAteKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 697, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblData, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDtVendaDe, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblAté, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(txtDtVendaAte, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cmdBuscar)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblData)
                    .addComponent(cmdBuscar)
                    .addComponent(txtDtVendaDe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAté)
                    .addComponent(txtDtVendaAte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 328, Short.MAX_VALUE)
                .addContainerGap())
        );

        lblData.getAccessibleContext().setAccessibleName("");
        lblData.getAccessibleContext().setAccessibleDescription("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        setSize(new java.awt.Dimension(733, 443));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cmdBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdBuscarActionPerformed
        String DtInicio = "", DtFim = "";
        List<Pedido> listVenda = null;

        DtInicio = txtDtVendaDe.getText();
        DtInicio = DtInicio.replace("/", "");

        DtFim = txtDtVendaAte.getText();
        DtFim = DtFim.replace("/", "");

        if (DtInicio.trim().equals("")) {
            JOptionPane.showMessageDialog(null, "Data de inicio não preenchida");
            return;
        }

        if (DtFim.trim().equals("")) {
            JOptionPane.showMessageDialog(null, "Data de fim não preenchida");
            return;
        }

        try {
            listVenda = PedidoDAO.getPedidosRel(txtDtVendaDe.getText(), txtDtVendaAte.getText());
        } catch (Exception ex) {
            ex.printStackTrace();
        }

        DefaultTableModel model = (DefaultTableModel) tabelaResultado.getModel();
        model.setRowCount(0);

        if (listVenda == null || listVenda.size() <= 0) {
            JOptionPane.showMessageDialog(rootPane, "A pesquisa não retornou resultados ",
                    "Sem resultados", JOptionPane.ERROR_MESSAGE);

            return;
        }

        int size = listVenda.size();

        for (int i = 0; i < size; i++) {
            Pedido venda = listVenda.get(i);

            if (venda != null) {
                Object[] row = new Object[7];

                row[0] = venda.getCodigo();
                row[1] = venda.getCodigoCliente();
                row[2] = venda.getDtVenda();
                row[3] = venda.getVlTotal();
                row[4] = venda.getVlDesconto();
                row[5] = venda.getFormaPagto();
                row[6] = venda.getNotasInternas();
                model.addRow(row);
            }
        }

        // colocando colunas numéricas à direita
        DefaultTableCellRenderer alignmentDireita = new DefaultTableCellRenderer();
        alignmentDireita.setHorizontalAlignment(4); // 4 = direita

        tabelaResultado.getColumnModel().getColumn(2).setCellRenderer(alignmentDireita);
        tabelaResultado.getColumnModel().getColumn(3).setCellRenderer(alignmentDireita);

    }//GEN-LAST:event_cmdBuscarActionPerformed

    private void txtDtVendaAteKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDtVendaAteKeyReleased
        if (txtDtVendaAte.getText().equals("  /  /    ")) {
            txtDtVendaAte.setFocusLostBehavior(0); // COMMIT
        } else {
            txtDtVendaAte.setFocusLostBehavior(1); // COMMIT_OR_REVERT
        }
    }//GEN-LAST:event_txtDtVendaAteKeyReleased

    private void txtDtVendaDeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDtVendaDeKeyReleased
        if (txtDtVendaDe.getText().equals("  /  /    ")) {
            txtDtVendaDe.setFocusLostBehavior(0); // COMMIT
        } else {
            txtDtVendaDe.setFocusLostBehavior(1); // COMMIT_OR_REVERT
        }
    }//GEN-LAST:event_txtDtVendaDeKeyReleased

    private void txtDtVendaDeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDtVendaDeFocusLost
        if (txtDtVendaDe.getText().equals("  /  /    ")) {
            return;
        }

        DateFormat df = new SimpleDateFormat("dd/MM/yyyy");
        df.setLenient(false); // Se true, reajusta a data para um valor válido. Se false, não.

        try {
            df.parse(txtDtVendaDe.getText()); // data válida
        } catch (Exception ex) { // data inválida
            txtDtVendaDe.setText("");
            txtDtVendaDeKeyReleased(null);
        }
    }//GEN-LAST:event_txtDtVendaDeFocusLost

    private void txtDtVendaAteFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDtVendaAteFocusLost
        if (txtDtVendaAte.getText().equals("  /  /    ")) {
            return;
        }

        DateFormat df = new SimpleDateFormat("dd/MM/yyyy");
        df.setLenient(false); // Se true, reajusta a data para um valor válido. Se false, não.

        try {
            df.parse(txtDtVendaAte.getText()); // data válida
        } catch (Exception ex) { // data inválida
            txtDtVendaAte.setText("");
            txtDtVendaDeKeyReleased(null);
        }
    }//GEN-LAST:event_txtDtVendaAteFocusLost


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmdBuscar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAté;
    private javax.swing.JLabel lblData;
    private javax.swing.JTable tabelaResultado;
    private javax.swing.JFormattedTextField txtDtVendaAte;
    private javax.swing.JFormattedTextField txtDtVendaDe;
    // End of variables declaration//GEN-END:variables

    private void setToolTipText(String string) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
